### ISSUE TITLE
Potentially attempting to record null IPs 

### ISSUE THREAD

**Issue by dambrisco** [redditdota2league/server#212]
```
error: null value in column "ip" of relation "ip_address" violates not-null constraint
﻿
at Parser.parseErrorMessage (/src/node_modules/pg-protocol/dist/parser.js:287:98)
﻿
at Parser.handlePacket (/src/node_modules/pg-protocol/dist/parser.js:126:29)
﻿
at Parser.parse (/src/node_modules/pg-protocol/dist/parser.js:39:38)
﻿
at Socket.<anonymous> (/src/node_modules/pg-protocol/dist/index.js:11:42)
﻿
at Socket.emit (node:events:514:28)
﻿
at addChunk (node:internal/streams/readable:343:12)
﻿
at readableAddChunk (node:internal/streams/readable:316:9)
﻿
at Readable.push (node:internal/streams/readable:253:10)
﻿
at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
﻿
length: 207,
﻿
severity: 'ERROR',
﻿
code: '23502',
﻿
detail: 'Failing row contains (null, 108896499).',
﻿
hint: undefined,
﻿
position: undefined,
﻿
internalPosition: undefined,
﻿
internalQuery: undefined,
﻿
where: undefined,
﻿
schema: 'public',
﻿
table: 'ip_address',
﻿
column: 'ip',
﻿
dataType: undefined,
﻿
constraint: undefined,
﻿
file: 'execMain.c',
﻿
line: '1947',
﻿
routine: 'ExecConstraints'
﻿
}
```

**Comment by dambrisco** [comment]
Closed by #229
